# templates/secret-users.yaml — Kubernetes Secret с паролями пользователей ClickHouse
# Secret хранит конфиденциальные данные (пароли) в защифрованном виде (в etcd)
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}-users-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
type: Opaque
data:
  # Для каждого пользователя создаём две переменные окружения:
  # 1. CH_PASSWORD_<NAME>_PLAIN — пароль в открытом виде
  # 2. CH_PASSWORD_<NAME>_HEX — хеш пароля в SHA256 (hex формат)
  # ClickHouse использует хеши для безопасности
  {{- range .Values.users }}
  # Пароль пользователя {{ .name }} в открытом виде (base64)
  CH_PASSWORD_{{ .name | upper }}_PLAIN: {{ .password | b64enc | quote }}
  # Хеш пароля в SHA256 hex формате для использования в конфигурации
  CH_PASSWORD_{{ .name | upper }}_HEX: {{ .password | sha256sum | b64enc | quote }}
  {{- end }}
